name: Apply Terraform Code

on:
  pull_request:
    types: [assigned, opened, edited, synchronize, reopened]
    branches:
      - master
      - dev
      - uat
  push:
    branches:
      - master
      - dev
      - uat

jobs:
  create-infra:
    name: Setup Infrastructure
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-central-1
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Get Branch Name
        run: |
          if [ -z "${{ github.head_ref }}" ];
             then echo "BRANCH=${{ github.base_ref }}" >> $GITHUB_ENV;
             else echo "BRANCH=$( git rev-parse --abbrev-ref HEAD )" >> $GITHUB_ENV; 
          fi
          echo
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - run: echo "🤖Deploying to ${{ env.BRANCH }}."

      - name: "Setup Python 3.8"
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: "Test S3"
        run: aws s3 ls s3://apmechev-tfm-remote-state

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
          terraform_wrapper: false

      - run: ls
      - run: which python
      - run: which python3

      - name: "Terraform Init"
        run: terraform init
      
      - name: "Select Workspace"
        run: |
          if [[ -z $( terraform workspace list | grep ${{ env.BRANCH }} ) ]]; then terraform workspace new ${{ env.BRANCH }}; fi
          terraform workspace select ${{ env.BRANCH }} 
  
      - name: "Terraform Plan"
        run: terraform plan -var="branch_name=${{ env.BRANCH }}" -var="SECRET_KEY=${{ secrets.CAKEDAYS_SECRET_KEY }}"

      - name: "Terraform Apply"
        run: terraform apply -var="branch_name=${{ env.BRANCH }}" -var="SECRET_KEY=${{ secrets.CAKEDAYS_SECRET_KEY }}" -auto-approve

      - name: "Terraform Output"
        run: echo "$( terraform output -json  | jq -c . )" 

      - name: "Print Terraform Output"
        run: echo $( jq  .api_gateway_uri.value <<< $( terraform output -json )   )

      - name: Download Cake
        run: |
          SITE=$( jq .api_gateway_uri.value <<< $( terraform output -json  )  | sed -e 's/^"//' -e 's/"$//' )
          echo $SITE
          RES=$(curl -X POST -d {} $SITE)
          echo $RES
          if [[ ! "$( jq .Success <<< $RES )" == "true" ]]; then echo "Success value is " $( jq .success <<< $RES ); exit 1; fi
          if [[ -z "$( jq .cake <<< $RES |grep .ics)"  ]]; then echo " No .ics in cake result, Cake value is " $( jq .cake <<< $RES ); exit 1; fi