name: Create Test Environment

on:
  pull_request:
    types: [assigned, opened, edited, synchronize, reopened]
    branches:
      - master
      - dev
      - uat
  push:
    branches:
      - master
      - dev
      - uat

jobs:
  create-infra:
    name: Setup Infrastructure
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-central-1
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."

      - name: "Setup Python 3.8"
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - run: ls
      - run: which python
      - run: which python3

      - name: "Terraform Init"
        run: terraform init
      
      - name: "Select Workspace"
        run: terraform workspace select ${{ steps.extract_branch.outputs.branch }} || terraform workspace new ${{ steps.extract_branch.outputs.branch }}
  
      - name: "Terraform Plan"
        run: terraform plan var="branch_name=${{ steps.extract_branch.outputs.branch }}" -var="SECRET_KEY=${{ secrets.CAKEDAYS_SECRET_KEY }}"