name: Create Test Environment

on:
  pull_request:
    types: [assigned, opened, edited, synchronize, reopened]
    branches:
      - master
      - dev
      - uat

jobs:
  create-infra:
    name: Setup Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure/pr-module
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'eu-central-1'
    steps:
      - uses: actions/checkout@v2
      - run: |
        terraform init
        terraform workspace select $BRANCH_NAME || terraform workspace new $BRANCH_NAME
        terraform apply -var="branch_name=$BRANCH_NAME" -var="SECRET_KEY=${{secrets.CAKEDAYS_SECRET_KEY}}" -auto-approve
