name: Create Test Environment

on:
  pull_request:
    types: [assigned, opened, edited, synchronize, reopened]
    branches:
      - master
      - dev
      - uat
  push:
    branches:
      - master
      - dev
      - uat

jobs:
  create-infra:
    name: Setup Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure/pr-module
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-central-1
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}." 
      - name: "Setup Python 3.8"
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - run: ls
      - run: which python
      - run: which python3

      # - name: "Terraform Init"
      #   uses: hashicorp/terraform-github-actions@master
      #   with:
      #     tf_actions_version: 1.0.0
      #     tf_actions_subcommand: "init"

      # - name: "Terraform Plan"
      #   uses: hashicorp/terraform-github-actions@master
      #   with:
      #     tf_actions_version: 1.0.0
      #     tf_actions_subcommand: "plan"
      #     workspace: $BRANCH_NAME
      #     args: -var="branch_name=${{ github.head_ref }}"
      #           -var="SECRET_KEY=${{secrets.CAKEDAYS_SECRET_KEY}}

      # - name: "Terraform Apply"
      #   uses: hashicorp/terraform-github-actions@master
      #   with:
      #   tf_actions_version: 1.0.0
      #   tf_actions_subcommand: "apply"
      #   workspace: $BRANCH_NAME
      #   args: -var="branch_name=${{ github.head_ref }}"
      #         -var="SECRET_KEY=${{secrets.CAKEDAYS_SECRET_KEY}}
      #         -auto-approve