name: GitHub Actions Demo
on: [push]
jobs:
  create-infra:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: "Setup Python 3.8"
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - run: which python
      - run: which python3

      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Setup Python 3.8"
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - run: ls
    
      - name: "Terraform Init"
        uses: hashicorp/terraform-github-actions@master
        with:
        tf_actions_version: 1.0.0
        tf_actions_subcommand: "init"